### ISSUE TITLE
Image of crown not loading

### ISSUE THREAD

**Issue by lofifnc** [janhicken/challengescope#1]
The .svg of the crown is not shown on the button or above the player.
Following the embedded link will download/show the graphic.

Tested in:
* Google Chrome Version 56.0.2924.87 (64-bit)
* Firefox 53.0.3 (64-bit)

**Comment by lofifnc** [comment]
This could be an issue with darkhttpd not serving .svg

**Comment by lofifnc** [comment]
#2 Solves this issue by avoiding .svg

**Comment by janhicken** [comment]
It is indeed about darkhttpd serving the file with `Content-Type: application/octet-stream`.

This can be fixed by giving darkhttpd a mime type mapping file, e. g.:
```bash
$ darkhttpd . --mimetypes /etc/httpd/conf/mime.types
```
This uses the file from your Apache web server for example. 

As I'd rather use a scalable vector image, I'm going to close your PR.
